Insert into Departures(departureId, departureName)Values(departureIdSequence.nextVal, 'Терапевтическое');
Insert into Departures(departureId, departureName)Values(departureIdSequence.nextVal, 'Хирургическое');
Insert into Departures(departureId, departureName)Values(departureIdSequence.nextVal, 'Реанимации');
Insert into Departures(departureId, departureName)Values(departureIdSequence.nextVal, 'Неврологическое');
Insert into Departures(departureId, departureName)Values(departureIdSequence.nextVal, 'Гинекологическое');
Insert into Departures(departureId, departureName)Values(departureIdSequence.nextVal, 'Травматологическое');
Insert into Departures(departureId, departureName)Values(departureIdSequence.nextVal, 'Ревматологическое');
Insert into UsersTable(login,pass) Values ('igor','igor');

Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Павел','Попов','Дмитриевич',1,1);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Никита','Павлов','Павлович',2,1);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Андрей','Никитов','Никитьевич',1,1);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Сергей','Адреев','Андреевич',2,1);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Степан','Сергеев','Сергеевич',1,1);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Михаил','Степанов','Степанович',3,2);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Игорь','Михаилов','Михайлович',4,2);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Антон','Игорев','Игоревич',3,2);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Дмитрий','Антонов','Антонович',5,3);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Василий','Дмитриев','Дмитриевич',6,3);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Борис','Васильев','Васильевич',6,3);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Богдан','Борисов','Борисович',7,4);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Вадим','Богданов','Богданович',8,4);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Булат','Вадимов','Вадимович',8,4);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Валерий','Булатов','Булатович',7,4);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Виктор','Валерьев','Валерьевич',9,4);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Владислав','Викторов','Викторович',10,5);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Всеволод','Владиславов','Владиславович',10,5);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Вячеслав','Всеволодов','Всеволодович',10,5);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Виталий','Вяеславов','Вячеславович',11,6);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Геннадий','Витальев','Витальевич',11,6);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Глеб','Геннадьев','Геннадьевич',12,6);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Герман','Глебов','Глебович',13,7);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Георгий','Германов','Германович',13,7);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Григорий','Георгев','Георгевич',13,7);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Давид','Григорьев','Григорьевич',14,7);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Даниил','Давидов','Давидович',15,7);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Дамир','Даниилов','Даниилович',16,8);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Демьян','Дамиров','Дамирович',16,8);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Денис','Денисов','Денисович',17,8);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Евгений','Денисов','Денисович',18,9);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Евдоким','Евгеньев','Евгеньевич',18,9);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Егор','Евдокимов','Евдокимович',18,9);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Емельян','Егоров','Егорович',19,10);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Елисей','Емельянов','Емельянович',19,10);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Еремей','Елисеев','Елисеевич',19,10);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Захар','Еремеев','Еремеевич',20,10);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Ибрагим','Захаров','Захарович',21,10);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Камиль','Ибрагимов','Ибрагимович',22,11);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Игнат','Камильев','Камильевич',23,11);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Игорь','Игнатьев','Игнатьевич',24,11);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Ильгиз','Игорев','Игоревич',24,12);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Ильшат','Ильгизов','Ильгизович',23,12);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Илья','Ильшатов','Ильшатович',22,12);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Иннокентий','Ильев','Ильевич',25,13);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Исаак','Иннокентьев','Иннокентьевич',26,13);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Лев','Исааков','Исаакьевич',26,13);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Максим','Львов','Левович',26,13);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Марат','Максимов','Максимович',27,13);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Марк','Маратов','Маратович',27,14);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Мурат','Марков','Маркович',28,14);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Михаил','Муратов','Муратович',28,14);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Наиль','Михаилов','Михайлович',30,15);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Николай','Наильев','Наильевич',30,15);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Олег','Николаев','Николаевич',30,15);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Оливер','Олегов','Олегович',31,16);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Оскар','Оливеров','Оливерович',31,16);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Петр','Оскаров','Оскарович',32,16);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Потап','Петров','Петрович',32,16);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Прохар','Потапов','Потапович',33,16);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Равиль','Прохаров','Прохарович',33,17);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Рамазан','Равильев','Равильевич',34,17);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Ратмир','Рамазанов','Рамазанович',34,17);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Роман','Ратмиров','Ратмирович',36,18);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Руслан','Романов','Романович',35,18);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Рудольф','Русланов','Русланович',35,18);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Рустам','Рустамов','Рустамович',37,19);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Рафаэль','Рустамов','Рустамович',37,19);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Савва','Рафаэльев','Рафаэльевич',38,19);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Самат','Саввов','Саввович',39,19);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Сергей','Саматов','Саматович',38,19);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Тимур','Сергеев','Сергеевич',40,20);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Тарас','Тимуров','Тимурович',41,20);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Тамерлан','Тарасов','Тарасович',42,20);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Томас','Тамерланов','Тамерланович',40,21);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Федор','Томасов','Томасович',40,21);
Insert into People(peopleId,lastName,firstName,fatherName,diagnosisId,wardId)Values (peopleIdSequence.nextVal,'Эрик','Федоров','Федорович',37,21);